server:
  port: 9010

spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      routes:
        - id:
          uri:
          predicates:
      default-filters:

eureka:
  client:
    service-url: http://localhost:9000/eureka/
  instance:
    instance-id: gateway-server
    prefer-ip-address: true