# application.yml

spring:
  profiles:
    active: dev
  application:
    name: faraday-service

server:
  error:
    whitelabel:
      enabled: false

staffjoy:
  common:
    sentry-dsn: ${SENTRY_DSN}
    deploy-env: ${DEPLOY:V2}
  signing-secret: ${SIGNING_SECRET}

