# port
server:
  port: 8765

# DataSource
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    druid:
      # 主库数据源
      master:
        url: jdbc:mysql://127.0.0.1:3306/jpeony?characterEncoding=utf-8&useSSL=false
        username: root
        password: 123456
      # 从库数据源
      slave:
        # 从数据源开关/默认关闭
        enabled: true
        url: jdbc:mysql://127.0.0.1:3306/jpeony?characterEncoding=utf-8&useSSL=false
        username: root
        password: 123456
      # 初始连接数
      initialSize: 5
      # 最小连接池数量
      minIdle: 10
      # 最大连接池数量
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 6000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      # 配置一个连接在池中最大生存的时间，单位是毫秒
      maxEvictableIdleTimeMillis: 900000
      # 配置检测连接是否有效
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      webStatFilter:
        enabled: true
      statViewServlet:
        enabled: true
        # 设置白名单，不填则允许所有访问
        allow:
        url-pattern: /druid/*
        # 控制台管理用户名和密码
        login-username:
        login-password:
      filter:
        stat:
          enabled: true
          # 慢SQL记录
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true

# MyBatis
mybatis:
  mapper-locations: classpath:/config/mybatis/**/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true

# rocketmq
rocketmq:
  producer:
    test-producer:
      namesrvAddr: 10.6.202.110:9876;10.6.202.111:9876
      groupName: testProducerGroup
      topic: testTopic
      instanceName: testProducerInstance
  consumer:
    test-consumer:
      namesrvAddr: 10.6.202.110:9876;10.6.202.111:9876
      groupName: testConsumerGroup
      topic: testTopic
      tag: '*'
      batchMaxSize: 16
      instanceName: testConsumerInstance

# Swagger配置
swagger:
  isShow: true
  title: 接口文档
  description: 接口文档说明
  author: yihonglei
  version: V1.0