# tomcat 端口
server:
  port: 8080

# dubbo
dubbo:
  application:
    name: dubbo-rest
    owner: rest
  registry:
    address: zookeeper://39.98.65.20:2181,39.98.65.20:2182,39.98.65.20:2183
  scan:
    base-packages: com.jpeony.dubbo.rest