# https://matthewpalmer.net/kubernetes-app-developer/articles/kubernetes-apiversion-definition-guide.html
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: www-web-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: www-svc
        env: uat
        track: stable
    spec:
      containers:
        - name: www-svc
          image: boboweike/www-svc
          ports:
            - name: http-port
              containerPort: 80
          envFrom:
            - configMapRef:
                name: common-config
          volumeMounts:
            - name: logback-config-volume
              mountPath: /etc/staffjoy
      volumes:
        - name: logback-config-volume
          configMap:
            name: logback-config
---
apiVersion: v1
kind: Service
metadata:
  name: www-service
spec:
  selector:
    app: www-svc
    env: uat
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80