dubbo:
  application:
    name: cashier
    owner: yihonglei
  registry:
    address: zookeeper://127.0.0.1:2181
    check: true
    group: dubbo-dev
    simplified: true
  metadata-report:
    address: zookeeper://127.0.0.1:2181
    retry-times: 30
    cycle-report: false
    group: dubbo-dev
  scan:
    base-packages: com.jpeony.cashier