spring:
  profiles:
    active: dev
mybatis:
  mapper-locations: classpath*:com/jpeony/user/dal/persistence/*Mapper.xml"
  type-aliases-package: com.jpeony.user.dal.entitys

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
