spring:
  application:
    name: admin-gateway
  cloud:
    gateway:
      httpclient:
        connect-timeout: 1000
        response-timeout: 3s
      discovery:
        locator:
          enabled: false # 是否支持微服务名进行路径映射：true，允许，false ，不允许，一般用 false，否则会暴露服务
      enabled: true # 是否开启使用网关
      routes:
        - id: user-server # id 随意，但是必须要唯一
          uri: lb://user-server # nacos 中注册的服务 server 名字
          predicates:
            - Path=/user/** # 见到请求路径带 user，全部转发到 uri 对应路径，可以配置多个，比如 - Path=/user/**,/order/**
logging:
  level:
    root: info