server:
  port: 8081
#  ssl:
#    key-store: classpath:5690358_api.bzrrmedia.com.pfx
#    key-store-password: 6V10bCJ0
#    key-store-type: PKCS12

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/admin?characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
  resources:
    static-locations: classpath:/static/

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.example.entity

#showSql
logging:
  level:
    com:
      mhjy:
        mapper: debug