eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8001/eureka/
server:
  port: 8002
spring:
  application:
    name: zuul
  servlet:
    multipart:
      max-file-size: 100Mb
      max-request-size: 100Mb
ribbon:
    ReadTimeout: 60000
    ConnectTimeout: 60000
security:
  oauth2:
    client:
      access-token-uri: http://localhost:8005/oauth/token
      user-authorization-uri: http://localhost:8005/oauth/authorize
      client-id: app
    resource:
      user-info-uri: http://localhost:8005/user
      prefer-token-info: false



