# https://matthewpalmer.net/kubernetes-app-developer/articles/kubernetes-apiversion-definition-guide.html
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: app-spa-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: app-svc
        env: prod
    spec:
      containers:
        - name: app-spa
          image: boboweike/app-spa
          ports:
            - name: http-port
              containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  selector:
    app: app-svc
    env: prod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80