server:
  port: 8081

spring:
  shardingsphere:
    datasource: ###### 设置数据源 ######
      names: user-master,user-slave1,user-slave2
      user-master:
        type: com.alibaba.druid.pool.DruidDataSource # 指定数据库连接池
        driver-class-name: com.mysql.jdbc.Driver # 指定驱动
        url: jdbc:mysql://127.0.0.1:3306/user?characterEncoding=utf-8&useSSL=false # mysql 链接地址
        username: root # 用户名
        password: 123456 # 密码
        # 初始连接数
        initial-size: 5
        # 最小连接池数量
        min-idle: 10
        # 最大连接池数量
        max-active: 20
        # 配置获取连接等待超时的时间
        max-wait: 60000
        # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
        time-between-eviction-runs-millis: 6000
        # 配置一个连接在池中最小生存的时间，单位是毫秒
        min-evictable-idle-time-millis: 300000
        # 配置一个连接在池中最大生存的时间，单位是毫秒
        max-evictable-idle-time-millis: 900000
      user-slave1:
        type: com.alibaba.druid.pool.DruidDataSource # 指定数据库连接池
        driver-class-name: com.mysql.jdbc.Driver # 指定驱动
        url: jdbc:mysql://127.0.0.1:3306/user?characterEncoding=utf-8&useSSL=false # mysql 链接地址
        username: root # 用户名
        password: 123456 # 密码
        # 初始连接数
        initial-size: 5
        # 最小连接池数量
        min-idle: 10
        # 最大连接池数量
        max-active: 20
        # 配置获取连接等待超时的时间
        max-wait: 60000
        # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
        time-between-eviction-runs-millis: 6000
        # 配置一个连接在池中最小生存的时间，单位是毫秒
        min-evictable-idle-time-millis: 300000
        # 配置一个连接在池中最大生存的时间，单位是毫秒
        max-evictable-idle-time-millis: 900000
      user-slave2:
        type: com.alibaba.druid.pool.DruidDataSource # 指定数据库连接池
        driver-class-name: com.mysql.jdbc.Driver # 指定驱动
        url: jdbc:mysql://127.0.0.1:3306/user?characterEncoding=utf-8&useSSL=false # mysql 链接地址
        username: root # 用户名
        password: 123456 # 密码
        # 初始连接数
        initial-size: 5
        # 最小连接池数量
        min-idle: 10
        # 最大连接池数量
        max-active: 20
        # 配置获取连接等待超时的时间
        max-wait: 60000
        # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
        time-between-eviction-runs-millis: 6000
        # 配置一个连接在池中最小生存的时间，单位是毫秒
        min-evictable-idle-time-millis: 300000
        # 配置一个连接在池中最大生存的时间，单位是毫秒
        max-evictable-idle-time-millis: 900000
    sharding: # 配置默认数据源 user-master 默认数据源,主要用于写
      default-data-source-name: user-master
    masterslave: # 配置主从名称
      name: ms
      master-data-source-name: user-master # 置主库 master,负责数据的写入
      slave-data-source-names: user-slave1,user-slave2 # 配置从库 slave 节点
      load-balance-algorithm-type: round_robin # 配置 slave 节点的负载均衡均衡策略,采用轮询机制

# MyBatis
mybatis-plus:
  mapper-locations: classpath:mapper/**/**Mapper.xml
  configuration:
    map-underscore-to-camel-case: true