spring:
  shardingsphere:
    datasource: ###### 设置数据源 ######
      names: user-master,user-slave1,user-slave2
      user-master:
        type: com.zaxxer.hikari.HikariDataSource # 指定数据库连接池
        driver-class-name: com.mysql.jdbc.Driver # 指定驱动
        jdbc-url: jdbc:mysql://localhost:3306/user?characterEncoding=utf-8&useSSL=false # mysql 链接地址
        username: root # 用户名
        password: 123456 # 密码
      user-slave1:
        type: com.zaxxer.hikari.HikariDataSource # 指定数据库连接池
        driver-class-name: com.mysql.jdbc.Driver # 指定驱动
        jdbc-url: jdbc:mysql://localhost:3306/user?characterEncoding=utf-8&useSSL=false # mysql 链接地址
        username: root # 用户名
        password: 123456 # 密码
      user-slave2:
        type: com.zaxxer.hikari.HikariDataSource # 指定数据库连接池
        driver-class-name: com.mysql.jdbc.Driver # 指定驱动
        jdbc-url: jdbc:mysql://localhost:3306/user?characterEncoding=utf-8&useSSL=false # mysql 链接地址
        username: root # 用户名
        password: 123456 # 密码
    sharding: # 配置默认数据源 user-master 默认数据源,主要用于写
      default-data-source-name: user-master
    masterslave: # 配置主从名称
      name: ms
      master-data-source-name: user-master # 置主库 master,负责数据的写入
      slave-data-source-names: user-slave1,user-slave2 # 配置从库 slave 节点
      load-balance-algorithm-type: round_robin # 配置 slave 节点的负载均衡均衡策略,采用轮询机制
    props:
      sql:
        show: true

# MyBatis-Plus
mybatis-plus:
  mapper-locations: classpath:mapper/**/**Mapper.xml
  configuration:
    map-underscore-to-camel-case: true