spring:
  profiles:
    active: prod
mybatis:
  mapper-locations: classpath*:com/jpeony/comment/dal/persistence/*Mapper.xml"
  type-aliases-package: com.jpeony.comment.dal.entitys
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql