# tomcat 端口
server:
  port: 8081

# dubbo
dubbo:
  application:
    name: user-server
    owner: user
  registry:
    address: zookeeper://39.98.65.20:2181,39.98.65.20:2182,39.98.65.20:2183
  protocol:
    name: dubbo
    port: 20880
  scan:
    base-packages: com.jpeony.dubbo.user.provider.services