eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8001/eureka/
#security:
#  basic:
#    enabled: false
server:
  port: 8005
spring:
  application:
    name: api-admin
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/clouddo?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8
mybatis:
  mapper-locations: mapper/**Mapper.xml
  configuration:
      map-underscore-to-camel-case: true
#logging:
#  level: debug